<?xml version="1.0" encoding="utf-8"?>
<LOG>
  <LOG ID="708059777" Data="21/01/2017 11:27:19">
    <Sessao>kxgwsncexs5hiy441logju32</Sessao>
    <IP>::1</IP>
    <HostName>DESKTOP-5TKHUUF\André</HostName>
    <Mensagem>Erro de rede ou específico à instância ao estabelecer conexão com o SQL Server. O servidor não foi encontrado ou não estava acessível. Verifique se o nome da instância está correto e se o SQL Server está configurado para permitir conexões remotas. (provider: SQL Network Interfaces, error: 26 - Erro ao Localizar Servidor/Instância Especificada) *** The underlying provider failed on Open.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; condomino/avatar</NameSpace>
    <Context />
    <StackTrace>   em System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   em System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   em System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   em System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;&gt;c__DisplayClass7.&lt;GetResults&gt;b__5()
   em System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   em System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   em System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;System.Collections.Generic.IEnumerable&lt;T&gt;.GetEnumerator&gt;b__0()
   em System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   em System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   em System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.&lt;GetElementFunction&gt;b__2[TResult](IEnumerable`1 sequence)
   em System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   em System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   em System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   em System.Data.Entity.Internal.Linq.InternalSet`1.FindInStore(WrappedEntityKey key, String keyValuesParamName)
   em System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
   em System.Data.Entity.DbSet`1.Find(Object[] keyValues)
   em App_Dominio.Security.EmpresaSecurity`1._ValidarSessao(String sessionId) na C:\Sistemas\app_dominio\App_Dominio\App_Dominio\Security\EmpresaSecurity.cs:linha 225</StackTrace>
  </LOG>
  <LOG ID="1590984380" Data="21/01/2017 11:27:19">
    <Sessao>kxgwsncexs5hiy441logju32</Sessao>
    <IP>::1</IP>
    <HostName>DESKTOP-5TKHUUF\André</HostName>
    <Mensagem>Erro de rede ou específico à instância ao estabelecer conexão com o SQL Server. O servidor não foi encontrado ou não estava acessível. Verifique se o nome da instância está correto e se o SQL Server está configurado para permitir conexões remotas. (provider: SQL Network Interfaces, error: 26 - Erro ao Localizar Servidor/Instância Especificada) *** The underlying provider failed on Open.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.SecurityContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; condomino/avatar</NameSpace>
    <Context />
    <StackTrace>   em System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   em System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   em System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   em System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;&gt;c__DisplayClass7.&lt;GetResults&gt;b__5()
   em System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   em System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   em System.Data.Entity.Core.Objects.ObjectQuery`1.&lt;System.Collections.Generic.IEnumerable&lt;T&gt;.GetEnumerator&gt;b__0()
   em System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   em System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   em System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.&lt;GetElementFunction&gt;b__2[TResult](IEnumerable`1 sequence)
   em System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   em System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   em System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   em System.Data.Entity.Internal.Linq.InternalSet`1.FindInStore(WrappedEntityKey key, String keyValuesParamName)
   em System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
   em System.Data.Entity.DbSet`1.Find(Object[] keyValues)
   em App_Dominio.Security.EmpresaSecurity`1._ValidarSessao(String sessionId) na C:\Sistemas\app_dominio\App_Dominio\App_Dominio\Security\EmpresaSecurity.cs:linha 225</StackTrace>
  </LOG>
  <LOG ID="2137147704" Data="21/01/2017 11:37:48">
    <Sessao>kxgwsncexs5hiy441logju32</Sessao>
    <IP>::1</IP>
    <HostName>DESKTOP-5TKHUUF\André</HostName>
    <Mensagem>The underlying provider failed on Open.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="eXqMJ8hQ93J9uVbUq0_WqTJ5pPGqzGvvnbjNAp2WPAaat90MvyxNLugpHXNG9y2SQGmYgawOdgoY_SQsN7J6GuFm7J5Dpbg812Sl93Hpark1",UserName="andreborgesleal@live.com",Password="EvergladesParc"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="1530719913" Data="21/01/2017 11:37:48">
    <Sessao>kxgwsncexs5hiy441logju32</Sessao>
    <IP>::1</IP>
    <HostName>DESKTOP-5TKHUUF\André</HostName>
    <Mensagem>The underlying provider failed on Open.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="eXqMJ8hQ93J9uVbUq0_WqTJ5pPGqzGvvnbjNAp2WPAaat90MvyxNLugpHXNG9y2SQGmYgawOdgoY_SQsN7J6GuFm7J5Dpbg812Sl93Hpark1",UserName="andreborgesleal@live.com",Password="EvergladesParc"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="1281834619" Data="21/01/2017 11:38:45">
    <Sessao>kxgwsncexs5hiy441logju32</Sessao>
    <IP>::1</IP>
    <HostName>DESKTOP-5TKHUUF\André</HostName>
    <Mensagem>The underlying provider failed on Open.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="mh7BPr8pss-qgCBbSFitut59eaIttuV1yfIpizVupDG_k4zxmmL-hSB7wCF9eCbMrD1whknjXMEM8Tl00q7A2uRTvnsi7NDOfuqGv3C99sM1",UserName="andreborgesleal@live.com",Password="EvergladesParc"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="1700990656" Data="21/01/2017 11:38:45">
    <Sessao>kxgwsncexs5hiy441logju32</Sessao>
    <IP>::1</IP>
    <HostName>DESKTOP-5TKHUUF\André</HostName>
    <Mensagem>The underlying provider failed on Open.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="mh7BPr8pss-qgCBbSFitut59eaIttuV1yfIpizVupDG_k4zxmmL-hSB7wCF9eCbMrD1whknjXMEM8Tl00q7A2uRTvnsi7NDOfuqGv3C99sM1",UserName="andreborgesleal@live.com",Password="EvergladesParc"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="2095768098" Data="21/01/2017 11:39:28">
    <Sessao>kxgwsncexs5hiy441logju32</Sessao>
    <IP>::1</IP>
    <HostName>DESKTOP-5TKHUUF\André</HostName>
    <Mensagem>The underlying provider failed on Open.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="BjAKKENEVF9i6-0-TtXNgCD-m2CRxHzlWGnbe95qqQuxmk_msLKHTZDyFvMRMiINFDke-bEqux2j7E6YpzfocfQPCpkn9aJy5L6slP8B9GE1",UserName="andreborgesleal@live.com",Password="EvergladesParc"</Context>
    <StackTrace />
  </LOG>
  <LOG ID="367440488" Data="21/01/2017 11:39:28">
    <Sessao>kxgwsncexs5hiy441logju32</Sessao>
    <IP>::1</IP>
    <HostName>DESKTOP-5TKHUUF\André</HostName>
    <Mensagem>The underlying provider failed on Open.</Mensagem>
    <NameSpace>App_Dominio.Security.EmpresaSecurity`1[[App_Dominio.Entidades.App_DominioContext, App_Dominio, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] =&gt; </NameSpace>
    <Context>__RequestVerificationToken="BjAKKENEVF9i6-0-TtXNgCD-m2CRxHzlWGnbe95qqQuxmk_msLKHTZDyFvMRMiINFDke-bEqux2j7E6YpzfocfQPCpkn9aJy5L6slP8B9GE1",UserName="andreborgesleal@live.com",Password="EvergladesParc"</Context>
    <StackTrace />
  </LOG>
</LOG>